# Stubs for torchvision.models.detection (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .faster_rcnn import *
from .mask_rcnn import *
from .keypoint_rcnn import *
