# Stubs for torchvision.models.detection.backbone_utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .._utils import IntermediateLayerGetter
from torch import nn
from typing import Any

class BackboneWithFPN(nn.Sequential):
    out_channels: Any = ...
    def __init__(self, backbone: Any, return_layers: Any, in_channels_list: Any, out_channels: Any) -> None: ...

def resnet_fpn_backbone(backbone_name: Any, pretrained: Any): ...
