# Stubs for torchvision (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .version import __version__
from typing import Any

def set_image_backend(backend: Any) -> None: ...
def get_image_backend(): ...
