# Stubs for torchvision.utils (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

irange = range

def make_grid(tensor: Any, nrow: int = ..., padding: int = ..., normalize: bool = ..., range: Optional[Any] = ..., scale_each: bool = ..., pad_value: int = ...): ...
def save_image(tensor: Any, filename: Any, nrow: int = ..., padding: int = ..., normalize: bool = ..., range: Optional[Any] = ..., scale_each: bool = ..., pad_value: int = ...) -> None: ...
