# Stubs for torchvision.models (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .alexnet import *
from .resnet import *
from .vgg import *
from .squeezenet import *
from .inception import *
from .densenet import *
from .googlenet import *
from .mobilenet import *
from .shufflenetv2 import *
