# Stubs for torchvision.models.segmentation (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .segmentation import *
from .fcn import *
from .deeplabv3 import *
