# Stubs for torchvision.models.segmentation.fcn (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from ._utils import _SimpleSegmentationModel
from torch import nn
from typing import Any

class FCN(_SimpleSegmentationModel): ...

class FCNHead(nn.Sequential):
    def __init__(self, in_channels: Any, channels: Any) -> None: ...
