# Stubs for torchvision.ops (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .boxes import nms as nms
from .feature_pyramid_network import FeaturePyramidNetwork as FeaturePyramidNetwork
from .poolers import MultiScaleRoIAlign as MultiScaleRoIAlign
from .roi_align import RoIAlign as RoIAlign, roi_align as roi_align
from .roi_pool import RoIPool as RoIPool, roi_pool as roi_pool
