# Stubs for torchvision.ops.misc (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import torch
from typing import Any, Optional

class _NewEmptyTensorOp(torch.autograd.Function):
    @staticmethod
    def forward(ctx: Any, x: Any, new_shape: Any): ...
    @staticmethod
    def backward(ctx: Any, grad: Any): ...

class Conv2d(torch.nn.Conv2d):
    def forward(self, x: Any): ...

class ConvTranspose2d(torch.nn.ConvTranspose2d):
    def forward(self, x: Any): ...

class BatchNorm2d(torch.nn.BatchNorm2d):
    def forward(self, x: Any): ...

def interpolate(input: Any, size: Optional[Any] = ..., scale_factor: Optional[Any] = ..., mode: str = ..., align_corners: Optional[Any] = ...): ...

class FrozenBatchNorm2d(torch.jit.ScriptModule):
    def __init__(self, n: Any) -> None: ...
    def forward(self, x: Any): ...
